/****************************************************************************
**
** Metadata for SMSManager generated by dumpcpp v5.6.0 using
** D:\develop\sdk\qt\win32\5.6\msvc2015\bin\dumpcpp.exe -compat -n SMSManager -o SMSManager {4892F679-C799-439A-828D-3C7592D4D201}
** from the type library C:\Program Files\ForwardT Software\FDTitle\SMSObjMgr.exe
**
****************************************************************************/

#define QAX_DUMPCPP_SMSMANAGER_NOINLINES
#include "SMSManager.h"

using namespace SMSManager;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[69];
    char stringdata0[805];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 22, 0),
QT_MOC_LITERAL(1, 23, 9, 0),
QT_MOC_LITERAL(2, 33, 0, 0),
QT_MOC_LITERAL(3, 34, 4, 0),
QT_MOC_LITERAL(4, 39, 6, 0),
QT_MOC_LITERAL(5, 46, 4, 0),
QT_MOC_LITERAL(6, 51, 4, 0),
QT_MOC_LITERAL(7, 56, 15, 0),
QT_MOC_LITERAL(8, 72, 4, 0),
QT_MOC_LITERAL(9, 77, 6, 0),
QT_MOC_LITERAL(10, 84, 4, 0),
QT_MOC_LITERAL(11, 89, 4, 0),
QT_MOC_LITERAL(12, 94, 6, 0),
QT_MOC_LITERAL(13, 101, 9, 0),
QT_MOC_LITERAL(14, 111, 5, 0),
QT_MOC_LITERAL(15, 117, 13, 0),
QT_MOC_LITERAL(16, 131, 10, 0),
QT_MOC_LITERAL(17, 142, 4, 0),
QT_MOC_LITERAL(18, 147, 4, 0),
QT_MOC_LITERAL(19, 152, 10, 0),
QT_MOC_LITERAL(20, 163, 5, 0),
QT_MOC_LITERAL(21, 169, 15, 0),
QT_MOC_LITERAL(22, 185, 13, 0),
QT_MOC_LITERAL(23, 199, 8, 0),
QT_MOC_LITERAL(24, 208, 13, 0),
QT_MOC_LITERAL(25, 222, 8, 0),
QT_MOC_LITERAL(26, 231, 6, 0),
QT_MOC_LITERAL(27, 238, 8, 0),
QT_MOC_LITERAL(28, 247, 11, 0),
QT_MOC_LITERAL(29, 259, 11, 0),
QT_MOC_LITERAL(30, 271, 8, 0),
QT_MOC_LITERAL(31, 280, 7, 0),
QT_MOC_LITERAL(32, 288, 27, 0),
QT_MOC_LITERAL(33, 316, 12, 0),
QT_MOC_LITERAL(34, 329, 7, 0),
QT_MOC_LITERAL(35, 337, 15, 0),
QT_MOC_LITERAL(36, 353, 16, 0),
QT_MOC_LITERAL(37, 370, 17, 0),
QT_MOC_LITERAL(38, 388, 29, 0),
QT_MOC_LITERAL(39, 418, 11, 0),
QT_MOC_LITERAL(40, 430, 18, 0),
QT_MOC_LITERAL(41, 449, 11, 0),
QT_MOC_LITERAL(42, 461, 13, 0),
QT_MOC_LITERAL(43, 475, 11, 0),
QT_MOC_LITERAL(44, 487, 10, 0),
QT_MOC_LITERAL(45, 498, 11, 0),
QT_MOC_LITERAL(46, 510, 15, 0),
QT_MOC_LITERAL(47, 526, 19, 0),
QT_MOC_LITERAL(48, 546, 5, 0),
QT_MOC_LITERAL(49, 552, 18, 0),
QT_MOC_LITERAL(50, 571, 4, 0),
QT_MOC_LITERAL(51, 576, 16, 0),
QT_MOC_LITERAL(52, 593, 18, 0),
QT_MOC_LITERAL(53, 612, 8, 0),
QT_MOC_LITERAL(54, 621, 4, 0),
QT_MOC_LITERAL(55, 626, 6, 0),
QT_MOC_LITERAL(56, 633, 5, 0),
QT_MOC_LITERAL(57, 639, 12, 0),
QT_MOC_LITERAL(58, 652, 4, 0),
QT_MOC_LITERAL(59, 657, 4, 0),
QT_MOC_LITERAL(60, 662, 7, 0),
QT_MOC_LITERAL(61, 670, 10, 0),
QT_MOC_LITERAL(62, 681, 7, 0),
QT_MOC_LITERAL(63, 689, 11, 0),
QT_MOC_LITERAL(64, 701, 17, 0),
QT_MOC_LITERAL(65, 719, 10, 0),
QT_MOC_LITERAL(66, 730, 16, 0),
QT_MOC_LITERAL(67, 747, 30, 0),
QT_MOC_LITERAL(68, 778, 25, 0)
    },
    "SMSManager::ISMSObject\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0"
    "signal\0argc\0argv\0Advise\0IUnknown*\0pIUnk\0GetStyleCount\0SetMessage\0Text\0Nick\0"
    "StyleIndex\0MsgID\0SetStyleMessage\0bstrNickStyle\0bstrNick\0bstrTextStyle\0bstrText\0"
    "lMsgID\0bNewLine\0TestMessage\0lStyleIndex\0UnAdvise\0control\0SMSManager::ISMSObjectCheck\0"
    "CheckMessage\0double&\0pfWidthFullness\0pfHeightFullness\0CheckStyleMessage\0"
    "SMSManager::SMSObjectsManager\0Interface 0\0ISMSObjectsManager\0Interface 1\0"
    "IRegistration\0Interface 2\0ISMSObject\0Interface 3\0ISMSObjectCheck\0GetSMSObjectByIndex\0"
    "Index\0GetSMSObjectByName\0Name\0GetSMSObjectName\0GetSMSObjectsCount\0Register\0"
    "pUnk\0GUID*&\0pGuid\0RenameByGuid\0GUID\0guid\0NewName\0Reregister\0OldName\0bstrSMSName\0"
    "SetStyleMessageTo\0Unregister\0UnregisterByGuid\0SMSManager::ISMSObjectsManager\0"
    "SMSManager::IRegistration\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_SMSManager__ISMSObject[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    9, 14, // methods
    1, 114, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 59, 2, 5,
    7, 1, 68, 2, 5,
    9, 3, 71, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 78, 2, 9,
    15, 0, 81, 2, 9,
    16, 4, 82, 2, 9,
    21, 6, 91, 2, 9,
    28, 4, 104, 2, 9,
    30, 0, 113, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19, 20,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 22, 23, 24, 25, 26, 27,
    QMetaType::Double, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 25, 23, 29, 26,
    QMetaType::Void,

 // properties: name, type, flags
    31, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ISMSObject::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_SMSManager__ISMSObject, 0, 0, 0 }
};

void *ISMSObject::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "SMSManager::ISMSObject"))
        return static_cast<void*>(const_cast<ISMSObject*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_SMSManager__ISMSObjectCheck[] = {

 // content:
    7, // revision
    32,  // classname
    0, 0, // classinfo
    5, 14, // methods
    1, 84, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 39, 2, 5,
    7, 1, 48, 2, 5,
    9, 3, 51, 2, 5,

// slot: name, argc, parameters, tag, flags
    33, 5, 58, 2, 9,
    37, 7, 69, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Int, 0x80000000 | 34, 0x80000000 | 34, 25, 23, 29, 35, 36,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, 0x80000000 | 34, 0x80000000 | 34, 22, 23, 24, 25, 27, 35, 36,

 // properties: name, type, flags
    31, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ISMSObjectCheck::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_SMSManager__ISMSObjectCheck, 0, 0, 0 }
};

void *ISMSObjectCheck::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "SMSManager::ISMSObjectCheck"))
        return static_cast<void*>(const_cast<ISMSObjectCheck*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_SMSManager__SMSObjectsManager[] = {

 // content:
    7, // revision
    38,  // classname
    4, 14, // classinfo
    22, 22, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    39, 40, 
    41, 42, 
    43, 44, 
    45, 46, 

// signal: name, argc, parameters, tag, flags
    1, 4, 132, 2, 5,
    7, 1, 141, 2, 5,
    9, 3, 144, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 151, 2, 9,
    33, 5, 154, 2, 9,
    37, 7, 165, 2, 9,
    47, 1, 180, 2, 9,
    49, 1, 183, 2, 9,
    51, 1, 186, 2, 9,
    52, 0, 189, 2, 9,
    15, 0, 190, 2, 9,
    53, 3, 191, 2, 9,
    57, 2, 198, 2, 9,
    61, 2, 203, 2, 9,
    16, 5, 208, 2, 9,
    16, 4, 219, 2, 9,
    21, 6, 228, 2, 9,
    64, 7, 241, 2, 9,
    28, 4, 256, 2, 9,
    30, 0, 265, 2, 9,
    65, 1, 266, 2, 9,
    66, 1, 269, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, 0x80000000 | 13, 14,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Int, 0x80000000 | 34, 0x80000000 | 34, 25, 23, 29, 35, 36,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, 0x80000000 | 34, 0x80000000 | 34, 22, 23, 24, 25, 27, 35, 36,
    0x80000000 | 13, QMetaType::Int, 48,
    0x80000000 | 13, QMetaType::QString, 50,
    QMetaType::QString, QMetaType::Int, 48,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Void, 0x80000000 | 13, QMetaType::QString, 0x80000000 | 55, 54, 50, 56,
    QMetaType::Void, 0x80000000 | 58, QMetaType::QString, 59, 60,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 62, 60,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 63, 25, 23, 29, 26,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19, 20,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 22, 23, 24, 25, 26, 27,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 63, 22, 23, 24, 25, 26, 27,
    QMetaType::Double, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 25, 23, 29, 26,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 50,
    QMetaType::Void, 0x80000000 | 58, 59,

    0 // eod
};

const QMetaObject SMSObjectsManager::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_SMSManager__SMSObjectsManager, 0, 0, 0 }
};

void *SMSObjectsManager::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "SMSManager::SMSObjectsManager"))
        return static_cast<void*>(const_cast<SMSObjectsManager*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_SMSManager__ISMSObjectsManager[] = {

 // content:
    7, // revision
    67,  // classname
    0, 0, // classinfo
    9, 14, // methods
    1, 114, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 59, 2, 5,
    7, 1, 68, 2, 5,
    9, 3, 71, 2, 5,

// slot: name, argc, parameters, tag, flags
    47, 1, 78, 2, 9,
    49, 1, 81, 2, 9,
    51, 1, 84, 2, 9,
    52, 0, 87, 2, 9,
    16, 5, 88, 2, 9,
    64, 7, 99, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    0x80000000 | 13, QMetaType::Int, 48,
    0x80000000 | 13, QMetaType::QString, 50,
    QMetaType::QString, QMetaType::Int, 48,
    QMetaType::Int,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 63, 25, 23, 29, 26,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 63, 22, 23, 24, 25, 26, 27,

 // properties: name, type, flags
    31, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ISMSObjectsManager::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_SMSManager__ISMSObjectsManager, 0, 0, 0 }
};

void *ISMSObjectsManager::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "SMSManager::ISMSObjectsManager"))
        return static_cast<void*>(const_cast<ISMSObjectsManager*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_SMSManager__IRegistration[] = {

 // content:
    7, // revision
    68,  // classname
    0, 0, // classinfo
    8, 14, // methods
    1, 96, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 54, 2, 5,
    7, 1, 63, 2, 5,
    9, 3, 66, 2, 5,

// slot: name, argc, parameters, tag, flags
    53, 3, 73, 2, 9,
    57, 2, 80, 2, 9,
    61, 2, 85, 2, 9,
    65, 1, 90, 2, 9,
    66, 1, 93, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, 0x80000000 | 13, QMetaType::QString, 0x80000000 | 55, 54, 50, 56,
    QMetaType::Void, 0x80000000 | 58, QMetaType::QString, 59, 60,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 62, 60,
    QMetaType::Void, QMetaType::QString, 50,
    QMetaType::Void, 0x80000000 | 58, 59,

 // properties: name, type, flags
    31, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IRegistration::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_SMSManager__IRegistration, 0, 0, 0 }
};

void *IRegistration::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "SMSManager::IRegistration"))
        return static_cast<void*>(const_cast<IRegistration*>(this));
    return QAxObject::qt_metacast(_clname);
}

